name: CI/CD Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14'

    - name: Install dependencies
      run: npm install
      working-directory: ./my-aws-app/my-app

    - name: Build the app
      run: npm run build
      working-directory: ./my-aws-app/my-app

    - name: Install Playwright browsers
      run: npx playwright install --with-deps

    - name: Start server
      run: npm start &
      env:
        BROWSER: none # This ensures that the server does not open a browser

    - name: Sleep to allow server to start
      run: sleep 10

    - name: Run tests
      run: npx playwright test
      working-directory: ./my-aws-app/my-app/tests

    - name: Stop server
      run: kill $(lsof -t -i:3000)

    - name: Upload production-ready build files
      uses: actions/upload-artifact@v2
      with:
        name: production-files
        path: ./my-aws-app/my-app/build
